CREATE TABLE EXPENSE(
	EXPID VARCHAR(20) UNIQUE NOT NULL,
	EXP_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	TRANSID VARCHAR(20) NOT NULL,
	VENDORID VARCHAR(20) NOT NULL,
	TOTAL_COST NUMERIC(10) NOT NULL,
	PAYMENT_MODE VARCHAR(30)
);

CREATE TABLE ITEM(
	ITEMID VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL,
	LAST_MODIFIED DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE CATEGORY(
	CATEGORYID VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL,
	LAST_MODIFIED DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE VENDOR(
	VENDORID VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(20) NOT NULL,
	LAST_MODIFIED DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE TRANSACTION(
	TRANSID VARCHAR(20) NOT NULL,
	ITEMID VARCHAR(20)  NOT NULL,
	CATEGORYID VARCHAR(20) NOT NULL,
	COST NUMERIC(10) NOT NULL,
	QUANTITY NUMERIC(10) NOT NULL,
	METRIC VARCHAR(10) NOT NULL,
	PRIMARY KEY(TRANSID, ITEMID,CATEGORYID)
);

COMMIT;